version: '3.8'

services:
  stories:
    build: ./service-stories
    container_name: stories
    ports:
      - "8001:8001"
    volumes:
      - ./service-stories:/app
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
  auth:
    build: ./service-auth
    container_name: auth
    ports:
      - "5122:5122"
    volumes:
      - ./service-auth:/app
  db:
    image: postgres:16
    environment: 
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432
