[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["builder555", "mcraa"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.109.2"
uvicorn = "^0.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
